name: PhpUnit

on: [ push, pull_request ]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    -   php: '7.4'
                    -   php: '8.0'
        env:
            extensions: bcmath gd xdebug
            XDEBUG_MODE: coverage
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v6
                with:
                    php_version: '${{ matrix.php }}'
                    php_extensions: "${{ env.extensions }}"
            -   uses: php-actions/phpunit@v3
                with:
                    php_version: '${{ matrix.php }}'
                    php_extensions: "${{ env.extensions }}"
            - name: Coverage Report
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage
